# Generated by Django 5.2.15 on 2026-06-29 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=10)),
                ('purity', models.CharField(choices=[('24K', '24 Karat (999)'), ('22K', '22 Karat (916)'), ('18K', '18 Karat (750)'), ('14K', '14 Karat (585)'), ('STERLING', 'Sterling Silver (92.5%)'), ('FINE_SILVER', 'Fine Silver (99.9%)')], max_length=15)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Metal Rate',
                'verbose_name_plural': 'Metal Rates',
                'ordering': ['-effective_date', 'metal'],
                'unique_together': {('metal', 'purity', 'effective_date')},
            },
        ),
    ]
