# Generated by Django 5.2.15 on 2026-06-29 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('RING', 'Ring'), ('NECKLACE', 'Necklace'), ('CHAIN', 'Chain'), ('BANGLE', 'Bangle'), ('BRACELET', 'Bracelet'), ('EARRINGS', 'Earrings'), ('PENDANT', 'Pendant'), ('COIN_BAR', 'Coin / Bar'), ('WATCH', 'Watch'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(help_text="e.g. 'Floral design gold ring with red stone, slightly worn'", max_length=255)),
                ('metal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('PLATINUM', 'Platinum'), ('OTHER', 'Other / Mixed')], max_length=10)),
                ('purity', models.CharField(choices=[('24K', '24 Karat (999)'), ('22K', '22 Karat (916)'), ('18K', '18 Karat (750)'), ('14K', '14 Karat (585)'), ('STERLING', 'Sterling Silver (92.5%)'), ('FINE_SILVER', 'Fine Silver (99.9%)'), ('NA', 'Not Applicable')], max_length=15)),
                ('gross_weight_grams', models.DecimalField(decimal_places=3, max_digits=8)),
                ('stone_weight_grams', models.DecimalField(decimal_places=3, default=0, help_text='Weight of non-metal stones/gems to deduct from gross weight', max_digits=8)),
                ('net_weight_grams', models.DecimalField(decimal_places=3, editable=False, max_digits=8)),
                ('appraised_value', models.DecimalField(decimal_places=2, help_text='Value assigned by staff at appraisal time (can be auto-suggested from the daily metal rate, then overridden)', max_digits=12)),
                ('status', models.CharField(choices=[('PLEDGED', 'Pledged (loan active)'), ('REDEEMED', 'Redeemed (returned to customer)'), ('AUCTIONED', 'Auctioned')], default='PLEDGED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='items.pledgeitem')),
            ],
        ),
    ]
