# Generated by Django 5.2.15 on 2026-06-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/photos/')),
                ('id_proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License'), ('OTHER', 'Other Government ID')], max_length=20)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('id_proof_document', models.FileField(blank=True, null=True, upload_to='customers/id_proofs/')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes about this customer')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
