# Generated by Django 5.2.15 on 2026-06-29 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, help_text='Monthly interest rate, e.g. 2.5 for 2.5% per month', max_digits=5)),
                ('interest_type', models.CharField(choices=[('FLAT_MONTHLY', 'Flat (on original principal)'), ('REDUCING', 'Reducing balance (on outstanding principal)')], default='FLAT_MONTHLY', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('tenure_months', models.PositiveIntegerField(default=3)),
                ('due_date', models.DateField(editable=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('REDEEMED', 'Redeemed'), ('AUCTIONED', 'Auctioned / Closed')], default='ACTIVE', max_length=20)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customer')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='items.pledgeitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_type', models.CharField(choices=[('INTEREST_ONLY', 'Interest Only'), ('PARTIAL', 'Partial Payment (Principal + Interest)'), ('FULL_REDEMPTION', 'Full Redemption')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('principal_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
